version: '3'
services:
  trojan-go:
    image: teddysun/trojan-go:latest # Этот образ поддерживает как amd64, так и arm64
    container_name: trojan-go
    restart: always
    ports:
      - "443:443"  # порт для trojan-go
    volumes:
      - ./config.json:/etc/trojan-go/config.json # монтируем каталог с конфигурационным файлом
      - ./cert:/cert
